### ISSUE TITLE
Error when running after meteor build

### ISSUE THREAD

**Issue by tgoldenberg** [thereactivestack-legacy/meteor-react-router-ssr#105]
In development this package works great! After I run `meteor build` and try to run my app with `node main.js`, I get this error:

```Cannot read property 'ServiceConfiguration' of undefined```

This prevents me from running a production version. Any suggestions? Greatly appreciate it!

**Comment by copleykj** [comment]
Any possibility of a reproduction?

**Comment by copleykj** [comment]
Closing this for now. Feel free to re-open with more information and a reproduction.
