### ISSUE TITLE
Support React Router v3 and v4

### ISSUE THREAD

**Issue by lvnr** [thereactivestack-legacy/meteor-react-router-ssr#106]
After updating to React Router v3.0.0, it seems to work normally, but throws this warning:

```
WARNING: npm peer requirements (for reactrouter:react-router-ssr) not installed:
 - react-router@3.0.0 installed, react-router@2.x needed
```

Also, since React Router v4 alpha is already out, do you have plans for making it work with it?

Thanks you!

**Comment by ansonla3** [comment]
any updates?

**Comment by CharlesOy** [comment]
Same suggestion here.

**Comment by Elviron** [comment]
Send a mail to benoit@thereactivestack.com to take over this repo and you can do whatever you want ;)

**Comment by copleykj** [comment]
Updated this to v3 for now
