### ISSUE TITLE
Wrong information returned from Meteor users collection

### ISSUE THREAD

**Issue by matth022** [thereactivestack-legacy/meteor-react-router-ssr#117]
When requiring documents (information) from the users collection, wrong information is sometimes provided (for the currently logged in user) for the own specified field 'score'.

For example in this container: 

```
import { Meteor } from 'meteor/meteor';
import { createContainer } from 'meteor/react-meteor-data';
import TopUsers from '../components/TopUsers.js';

export default createContainer(({ params }) => {
  const subscription = Meteor.subscribe('usersData.list.topusers');
  const loading = !subscription.ready();

  return {
      loading: loading,
      users: Meteor.users.find({}, {limit:10, sort:{score:-1}}).fetch(),
    };
}, TopUsers);
```

and on the server this is published:

```
Meteor.publish('usersData.list.topusers', function () {
    return Meteor.users.find({},
      {limit:10, sort:{score:-1},fields: {_id: 1,username: 1, profilePictureUrl: 1, score: 1}});
});
```

In this case the score of the logged in user (when equal to 0/ field not initialized yet), is sometimes provided as equal to the highest score of all the users returned. (usually when refreshing the page = when server is rendering)

Does someone have an idea why ? This is not happening when not using server side rendering...

**Comment by copleykj** [comment]
Can you provide a reproduction for this issue?

**Comment by matth022** [comment]
I figured out that when the field 'score' (on which sort is applied) is initialized for the logged in user, this issue doesn't happen anymore... but it is still strange that this didn't happen when ssr was not used. When the 'error' (wrong info provided) happened, a console.log on the users (provided through "Meteor.users.find({}, {limit:10, sort:{score:-1}}).fetch()" ) gave also the wrong information but when checking the mongo database via the shell, all the users had the right information... Do you understand what I mean ?
