### ISSUE TITLE
Wrong transform while ssr subscriptions

### ISSUE THREAD

**Issue by krizka** [thereactivestack-legacy/meteor-react-router-ssr#76]
https://github.com/thereactivestack/meteor-react-router-ssr/blob/master/lib/ssr_data.js#L35
This line breaks astronomy find methods with conversion to model objects.

**Comment by eXon** [comment]
Can you be more specific on what is the problem and what you need to be fixed? I'll need more context.

**Comment by copleykj** [comment]
Closing this. Feel free to reopen with more specifics about the issue and if possible a reproduction.
