### ISSUE TITLE
Issue with SubsManager

### ISSUE THREAD

**Issue by jschlieber** [thereactivestack-legacy/meteor-react-router-ssr#77]
First of all: Thank you for sharing this amazing project!

I migrated from flow-router-ssr to react-router-ssr. So far everything worked really well. But now I tried to use [SubsManager](https://github.com/kadirahq/subs-manager) for client side caching (what I also did with flow-router-ssr before). Server Side Rendering seems to be fine and the subscription is marked as ready on the client at initial page load. But when the data is fetched on the client (e.g. `Comments.find({}).fetch()`) nothing is there at the initial render.

Thus, the current user experience is like that: the page shows up almost immediately at first only to fall back into the loading state after some time and then eventually showing the initial data again. That's a no go...

This happend just by transitioning from `Meteor.subscribe` to `MySubsManager.subscribe`.

I'm using Meteor 1.3.4.4 and the latest version of react-router-ssr (3.1.3 at the moment of this writing).

**Comment by eXon** [comment]
Their is no special support for SubsManager. I'll gladly accept a PR that add this.
