### ISSUE TITLE
does it render html in the doc file?

### ISSUE THREAD

**Issue by kamil7732** [thereactivestack-legacy/meteor-react-router-ssr#88]
I'm trying to use this package. My question is should the package (I hope so) push rendered full html document to the client or only hydrated data? I've seen a website using this package and it has pushed full html while I can't figure out why I don't have it. I'm using normal subscriptions no redux.

deployment using mupc https://github.com/aadamsx/meteor-up-classic/tree/mupc-1.4
newest meteor

**Comment by copleykj** [comment]
If you are still using this package, give the latest version a try and if you still don't have full html then feel free to reopen this.
